name: Run Tests

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '**'
  release:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Validate pom.xml
        run: mvn clean validate --file pom.xml

      - name: Validate jar-pom.xml
        run: mvn clean validate --file jar-pom.xml

      - name: Run tests on main POM
        run: mvn clean test --file pom.xml
