name: Build and Publish RPM package

on:
  push:
    branches:
      - main
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: 'Build Maven'
        run: mvn -B clean package --file pom.xml

      - name: Build RPM package
        run: mvn -B clean package -DskipTests --file rpm/rpm-pom.xml

      - name: Upload RPM artifact
        uses: actions/upload-artifact@v4
        with:
          name: rpm-package
          path: rpm/target/rpm/

  release:
    needs: build
    if: github.event_name == 'release' && github.event.action == 'created'
    runs-on: ubuntu-latest

    steps:
      - name: Download RPM artifact
        uses: actions/download-artifact@v4
        with:
          name: rpm-package
          path: rpms

      - name: Upload RPM to release
        uses: softprops/action-gh-release@v2
        with:
          files: rpms/**/*.rpm
